workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: app.kvittr
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm install -g @capacitor/cli
      - name: Build web app
        script: |
          npm run build
      - name: Capacitor sync
        script: |
          cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --archive-xcargs "-allowProvisioningUpdates"
    artifacts:
      - build/ios/ipa/*.ipa
