// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdfxfhchugungurebbcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZnhmaGNodWd1bmd1cmViYmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MjI5MDYsImV4cCI6MjA3Nzk5ODkwNn0.ab4LEebHRH0kV9pSX9OvjOXtBm_E8ZttdZK08bYYrog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});